<?php

namespace JuegoBundle\Repository;

/**
 * CaracteristicasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicasRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCaracteristicas($id)
	{
		$query = $this->createQueryBuilder('c')
			->select('c.fuerza', 'c.resistencia')
			->where('c.id = :id')
			->setParameter('id', $id)
			->getQuery();

		return $query->getResult();
	}

	public function updateCaracteristica($id, $caractToModify, $caract)
	{
		$query = $this->createQueryBuilder('c')
			->update()
			->set('c.'.$caractToModify, ':caract')
			->where('c.id = :id')
			->setParameter('id', $id)
			->setParameter('caract', $caract)
			->getQuery()
			->execute();

		return $query;
	}
}