<?php

namespace JuegoBundle\Repository;

/**
 * FuerzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuerzaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTiempo($id)
	{
		$query = $this->createQueryBuilder('f')
			->select('f.tiempo')
			->where('f.id = :id')
			->setParameter('id', $id)
			->getQuery();

		return $query->getResult();
	}
}
