<?php

namespace JuegoBundle\Repository;

/**
 * ModificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
