<?php

namespace JuegoBundle\Repository;

/**
 * ModificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificacionesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getModificacion($user, $accion) {
		$query = $this->createQueryBuilder('m')
			->where('m.valor = :accion')
			->andWhere('m.User = :user')
			->setParameter('accion', $accion)
			->setParameter('user', $user)
			->getQuery();

		return $query->getOneOrNullResult();
	}
}
