<?php

namespace JuegoBundle\Repository;

/**
 * ResistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResistenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
